### ISSUE TITLE
Can't resolve static files

### ISSUE THREAD

**Issue by mjrlowe** [mdubourg001/ssgo#1]
I'm getting a warning whenever I try to use static files (e.g. in the `src` attribute of an `img` tag):

**_post.html_**:
```html
...
<img src="image.jpg" alt="example image" />
...
```
**output**:
```
warning Could not resolve image.jpg inside of 'static/' dir: won't be included in output build.
```
This is despite having a `static` folder in the root directory with `image.jpg` inside.

I get a similar error even when I add a `/` and move the `image.jpg` file outside of the `static` folder:

_**post.html**_:

```html
...
<img src="/image.jpg" alt="example image" />
...
```
**output**:

```
warning Could not resolve /image.jpg: won't be included in output build.
```

**Comment by mdubourg001** [comment]
Hello ! Thanks for trying out ssgo and taking the time to fill an issue for this !

Can you give me a few more details about where this tag `<img src="image.jpg" alt="example image" />` is present in your project ? Is `post.html` a template a component ? Is the `<img>` tag it a top-level tag, or is it nested inside other tags ?

**Comment by mjrlowe** [comment]
`post.html` is in the templates folder and looks like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="title" eval:content="post.metas.title" />
    <title>My blog - {{ title }}</title>
  </head>
  <body>
    <img src="400.jpg"/>

    {{ content }}
  </body>
</html>
```

The content and title generate correctly, but the image doesn't work.

I also have a creator file (`creator.js`) in the `creators` folder which looks like this:
```javascript
export default function (buildPage) {

  const blogPosts = [{
      title: "hello world",
      content: "this is some example content",
      path: "post1"
    },
    {
      title: "post 2",
      content: "this is some more example content",
      path: "post2"
    },
  ]

  for (const post of blogPosts) {
    buildPage("post.html", post, {
      filename: post.path,
      dir: "pages/",
    });
  }
}
```

Everything seems to work fine except static files.

**Comment by mdubourg001** [comment]
I just tried with copy pasting the exact content you provided in an brand new ssgo project an it works well 🤔 

Can you please confirm that your project has the following structure ?
```
├── creators/
	└── creator.js
├── templates/
	└── post.html
└── static/
	└── 400.jpg
```

**Comment by mjrlowe** [comment]
Yes, it has that exact structure (as well as an empty `templates` folder and a generated `dist` folder).
I'll have a closer look later but I'm currently away from my computer so that may be in a while.

**Comment by mjrlowe** [comment]
Sorry it took so long to get back to you. I have made a [Github repository](https://github.com/TheWizardBear/ssgo-test) which has all the code for you to have a look at, since I can't seem to figure out what is wrong.

This is the output that I get when I run `ssgo`:

```
info ssgo 0.11.0
info Creating or emptying dist directory...
info Running creators\creator.js...
info Building dist\pages\post1.html...
warning Could not resolve 400.jpg inside of 'static/' dir: won't be included in output build.
info Building dist\pages\post2.html...
warning Could not resolve 400.jpg inside of 'static/' dir: won't be included in output build.
```

**Comment by mjrlowe** [comment]
Interestingly it adds `<img src="400.jpg"/>` to the final html file, even though it said it wouldn't.

**Comment by mdubourg001** [comment]
Ok thank you for the details, it seems like you are using ssgo on Windows am I right ? 

My guess is that it is a Windows related problem. I will try to reproduce on a Windows environment and fix the issue.

**Comment by mjrlowe** [comment]
Yes, I'm on Windows 10.

**Comment by mdubourg001** [comment]
Ok I just found what the issue was and pushed a fix: https://github.com/mdubourg001/ssgo/commit/9dd442bd133c33d5ca9f2a74170108277ba3fade

I then tagged a new version: v0.11.1
You'll just need to upgrade ssgo by re-installing using the `--force` flag.

**Comment by mdubourg001** [comment]
I'm closing this as this should work properly now. Thanks for reporting this 🙏

**Comment by mjrlowe** [comment]
Thank you! I think this fixed it.
