### ISSUE TITLE
[Feature] Recursive components rendering

### ISSUE THREAD

**Issue by acorello** [mdubourg001/ssgo#10]
I want to render a tree-like structure on a single page as nested lists. I thought of implementing that by recursively calling a component.

```HTML
<!-- FILE: components/bookmarks.html -->
<ul>
  <li for="node" of="bookmarks" if="node.type = 'folder'">
    <em>{{ node.name }}</em>
    <bookmarks bookmarks="node.bookmarks" />
  </li>
  <li for="node" of="bookmarks" if="node.type = 'bookmark'">
    <a href="node.href">{{ node.name }}</a>
  </li>
</ul>
```

This is a sample of the data I'd pass to the component with `<bookmarks bookmarks="bookmarks" />`

```ts
const BOOKMARKS: Bookmarks = [
  {
    type: "bookmark",
    name: "Rust Homepage",
    href: new URL("http://rust-lang.org"),
  },
  {
    type: "folder",
    name: "Awesome Projects",
    bookmarks: [
      {
        type: "bookmark",
        name: "Tokio (Homepage)",
        href: new URL("https://tokio.rs/"),
      },
    ],
  },
];
```

But, SSGO doesn't seem to allow recursive rendering. I'm a bit surprised because the diagram on the [quickstart](https://ssgo.netlify.app/docs/quickstart) page talks about "buildPage" recursively.
Where should I look to implement this feature? Would you discourage it? Can you suggest an alternative strategy to do what I need?

```txt
Error: When parsing 'bookmarks.html': Recursive call of component found.
    at Object.error (utils.ts:75:25)
    at checkRecursiveComponent (utils.ts:364:9)
    at checkRecursiveComponent (utils.ts:372:7)
    at checkRecursiveComponent (utils.ts:372:7)
    at build.ts:243:7
    at Array.forEach (<anonymous>)
    at computeCustomComponents (build.ts:242:12)
    at buildHtml (build.ts:384:7)
    at buildHtml (build.ts:413:7)
    at buildHtml (build.ts:413:7)
```

**Comment by mdubourg001** [comment]
Hi, thank you for taking the time to report this.

I must admit that I did not think all the cases through when adding this guard to prevent the recursive use of components: your need makes perfect sense and ssgo should not forbid it.

I think I will completely remove this guard and make it a warning instead. By the way, if you would want to make a PR for this, it would be very welcomed.

**Comment by mdubourg001** [comment]
I removed this guard in last version (v0.18.0, 3455eb1f5ff4b9e7e2bc8bb0435beb5b14c326c9), you should now be able to use components recursively just by upgrading by running: `ssgo upgrade`
