### ISSUE TITLE
Nest.land

### ISSUE THREAD

**Issue by michael-spengler** [mdubourg001/ssgo#5]
Hi ssgo folks 👍 

Would you mind if I published this module also on https://nest.land/ ?

I like having my dependencies persisted there. 

If you rather want to publish this module on https://nest.land/ yourself, please go for it - the publishing process is pretty straight forward.

Kind regards
Michael

**Comment by mdubourg001** [comment]
Hi there, 
I just published it, you can find it here: https://nest.land/package/ssgo

Thank you for your interest 👍
