### ISSUE TITLE
Dependencies need pinned versions

### ISSUE THREAD

**Issue by jakewhelan** [mdubourg001/ssgo#8]
This is a suggestion for one small change that would make `ssgo` much more stable in production.

Because of the instability of `std` and `deno` in general I'm having a bit of trouble using `ssgo` in production. Because dependencies aren't pinned/deterministic, each time I do a fresh install (in CI for example) the dependencies can (and have) differed, resulting in the build breaking due to weird dependency resolution issues. 

For the foreseeable future to facilitate using `ssgo` in production it would be really helpful if _all external dependencies_ had pinned versions.

Here's some example output from my latest installation of `ssgo` (0.16.1)

```
Warning Implicitly using latest version (0.74.0) for https://deno.land/std/flags/mod.ts
Warning Implicitly using latest version (0.74.0) for https://deno.land/std/ws/mod.ts
Warning Implicitly using latest version (v6.3.1) for https://deno.land/x/oak/mod.ts
```

I _have_ been able to build successfully at this time using `deno`@1.4.6, but my fear is that next time these implicit dependencies will resolve a version that breaks my build.

The solution is as simple as this:
```ts
// before
import { Application, Context, send } from "https://deno.land/x/oak/mod.ts";
```

```ts
// after
import { Application, Context, send } from "https://deno.land/x/oak@v6.3.1/mod.ts";
```

**Comment by jakewhelan** [comment]
There's also this:
```
Warning Implicitly using latest version (0.74.0) for https://deno.land/std/encoding/_yaml/loader/loader.ts
Warning Implicitly using latest version (0.74.0) for https://deno.land/std/encoding/_yaml/loader/loader.ts
Warning Implicitly using latest version (0.74.0) for https://deno.land/std/encoding/_yaml/loader/loader.ts
```

Not sure which dependency is belongs to at the moment.

**Comment by mdubourg001** [comment]
Hey, thank you for you contribution.

Versions are now pinned since the last release (v0.17.0), I'm closing this.
